Recover any files

diff --git a/setup/install b/setup/install
--- a/setup/install
+++ b/setup/install
@@ -2,11 +2,11 @@
 
 ### Error check
 
-set -x
-function error_handler() {
-  echo "ERROR" >&2
-  exit 1
-}
+#set -x
+#function error_handler() {
+#  echo "ERROR" >&2
+#  exit 1
+#}
 echo ' '
 echo '### Install ###'
 echo ' '
diff --git a/setup/uninstall b/setup/uninstall
--- a/setup/uninstall
+++ b/setup/uninstall
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-set -x
-function error_handler() {
-  echo "ERROR" >&2
-  exit 1
-}
+#set -x
+#function error_handler() {
+#  echo "ERROR" >&2
+#  exit 1
+#}
 
 echo '### Uninstall ###'
 
