Update/for debian linux (#21)
* Update many file for Debian linux

* Solved problem of version-default

* Solved problem of version-default

* Solved problem of version-default

diff --git a/setup/install b/setup/install
--- a/setup/install
+++ b/setup/install
@@ -3,12 +3,12 @@
 ### Error check
 
 #set -x
-#function error_handler() {
-#  echo "ERROR" >&2
-#  exit 1
-#}
+function error_handler() {
+  echo "ERROR" >&2
+  exit 1
+}
 echo ' '
-echo '### Install ###'
+echo ' ### Install ###'
 echo ' '
 #cd `dirname $0`
 
@@ -21,20 +21,22 @@ ver3='version-3'
 export PATH=$HOME/PyBox/pydoenv/bin:$PATH
 export PATH=$HOME/PyBox:$PATH
 
-if [ -f /usr/local/Homebrew ]; then
-  if [ -f /usr/bin/sudo ]; then
-    #sudo ln -si ~/PyBox/pybox /usr/local/bin
-    sudo cp ~/PyBox/pybox /usr/bin/
+if [ -f /bin/apt-get ]; then
+  echo ' This PC is Linux '
 
-  elif [ -e /usr/bin/sudo ]; then
-    cp ~/PyBox/pybox /usr/bin/
+  #if [ -f /usr/bin/sudo ]; then
+    #sudo ln -si ~/PyBox/pybox /usr/local/bin
+  #  sudo cp ~/PyBox/pybox /usr/bin/
+
+  #elif [ -e /usr/bin/sudo ]; then
+  #  cp ~/PyBox/pybox /usr/bin/
     #ln -si ~/PyBox/pybox /usr/local/bin
-  else
-    echo ' '
-    echo '### wait a next update ###'
-    echo ' '
-    exit 1
-  fi
+  #else
+  #  echo ' '
+  #  echo '### wait a next update ###'
+  #  echo ' '
+  #  exit 1
+  #fi
 elif [ -e /usr/local/Homebrew ]; then
   echo ' This PC is macOS '
 fi
@@ -71,19 +73,19 @@ fi
 #    exit 1
 #  fi
 
-if [ $1 == ${ver2} ]; then
+if [ $1 = ${ver2} ]; then
 
   echo ' '
   echo 'python2 has already finished support for pip'
   echo ' '
 
-elif [ $1 == ${ver3} ]; then
+elif [ $1 = ${ver3} ]; then
 
   if [ -f /usr/bin/python3 ]; then
-    
+
     if [ -f /usr/bin/sudo ]; then
 
-      if [ -e /usr/local/Homebrew ]; then 
+      if [ -e /usr/local/Homebrew ]; then
 
         echo ' '
         echo 'Maiking.......'
@@ -91,7 +93,7 @@ elif [ $1 == ${ver3} ]; then
         python3 -m venv pyboxenv ~/PyBox/pyboxenv
 
 
-      elif [ -f /usr/local/Homebrew ]; then
+      elif [ -f /bin/apt-get ]; then
 
         sudo apt-get install -y python3-venv python3-pip
         echo ' '
@@ -103,7 +105,7 @@ elif [ $1 == ${ver3} ]; then
 
     elif [ -e /usr/bin/sudo ]; then
 
-      if [ -e /usr/local/Homebrew ]; then 
+      if [ -e /usr/local/Homebrew ]; then
 
         echo ' '
         echo 'Maiking.......'
@@ -139,8 +141,10 @@ elif [ $1 == ${ver3} ]; then
   fi
 
 
-if [ $1 == ${ver} ]; then
+elif [ $1 = ${ver} ]; then
+
   if [ -f /usr/bin/python ]; then
+
     if [ -f /usr/bin/sudo ]; then
 
       if [ -f /usr/local/Homebrew ]; then
@@ -171,14 +175,50 @@ if [ $1 == ${ver} ]; then
       exit 1
     fi
 
-  elif [ -e /usr/bin/python ]; then
-    echo ' '
-    echo 'python is not defind'
-    echo ' '
-    exit 1
+  elif [ -f /usr/bin/python3 ]; then
+
+    if [ -f /usr/bin/sudo ]; then
+
+      if [ -e /usr/local/Homebrew ]; then
+
+        echo ' '
+        echo 'Maiking.......'
+        echo ' '
+        python3 -m venv pyboxenv ~/PyBox/pyboxenv
+
+
+      elif [ -f /bin/apt-get ]; then
+
+        sudo apt-get install -y python3-venv python3-pip
+        echo ' '
+        echo 'Maiking.......'
+        echo ' '
+        python3 -m venv pyboxenv ~/PyBox/pyboxenv
+      fi
+      exit 1
+
+    elif [ -e /usr/bin/sudo ]; then
+
+      if [ -e /usr/local/Homebrew ]; then
+
+        echo ' '
+        echo 'Maiking.......'
+        echo ' '
+        python3 -m venv pyboxenv ~/PyBox/pyboxenv
+
+
+      elif [ -f /usr/local/Homebrew ]; then
+        apt-get install -y python3-venv python3-pip
+        echo ' '
+        echo 'Maiking.......'
+        echo ' '
+        python3 -m venv pyboxenv ~/PyBox/pyboxenv
+      fi
+      exit 1
+    fi
   else
     echo ' '
-    echo '### wait a next update ###'
+    echo 'python is not defind'
     echo ' '
     exit 1
   fi
